### ISSUE TITLE
[CKEditor 5] Correcting a word doesn't work well with markers

### ISSUE THREAD

**Issue by Mgsy** [WebSpellChecker/wproofreader#14] opened 2019-08-06 11:44 UTC
To reproduce this issue it's required to run the editor with the comments plugin.

## Steps to reproduce
1. Insert the word "teswt".
2. Select it.
3. Add a new comment thread.
4. Hover the word.
5. Correct it to "testa".

## Current result
A part of the marker is lost.

**Comment by wsc-julia-shaptala** [comment] 2019-08-09 14:16
We think that this issue is related to #7 and your issue [#216](https://github.com/ckeditor/ckeditor5-typing/issues/216). It's related to the mechanism of handling text mutations by the editor. 

As it was mentioned in #7, we will try to use internal CKEditor 5 `input` command which should handle text replacing. 

But we hope that this issue and #7 will be fixed automatically after the issue [#216](https://github.com/ckeditor/ckeditor5-typing/issues/216) is resolved.

**Comment by Reinmar** [comment] 2019-08-13 07:09
We don't currently have a method which could handle this in a better way. The current `input` command overrides the content. We'd need a new type of command which would get markers and attributes into consideration.

I'll report a followup on our side.

**Comment by wsc-julia-shaptala** [comment] 2019-08-15 17:58
The fix for the issue has been released. We used CKE5's API: editor.execute( 'input', { text: 'hello' } ) as a temporary solution.
@Mgsy, please confirm if the issue is solved.

**Comment by Mgsy** [comment] 2019-08-27 07:11
>@Mgsy, please confirm if the issue is solved.

I've checked it and it's fixed.

**Comment by wsc-julia-shaptala** [comment] 2019-08-27 08:12
Great, thank you for the confirmation.

**Closed by wsc-julia-shaptala** 2019-08-27 08:12 UTC
Labels: integration:ckeditor5, resolution:fixed, status:confirmed, type:bug
